In [2]:
import numpy as np

# Step 1: Create 5x5 random integer array (0-9)
original = np.random.randint(0, 10, (5, 5))

# Step 2: Transform array (even -> 0, odd -> 1)
transformed = np.where(original % 2 == 0, 0, 1)

# Output
print("Original Matrix:\n", original)
print("\nTransformed Matrix:\n",transformed)

Original Matrix:
 [[2 4 4 8 2]
 [1 7 8 9 8]
 [5 8 8 0 7]
 [6 2 2 1 8]
 [4 3 0 9 3]]

Transformed Matrix:
 [[0 0 0 0 0]
 [1 1 0 1 0]
 [1 0 0 0 1]
 [0 0 0 1 0]
 [0 1 0 1 1]]
